#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -ex

cd web/themes/custom/badcamp_2018/

sudo apt-get update
sudo apt-get install nodejs
sudo apt-get install npm

npm install -g gulp
npm install
gulp sass