module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  camp_blog: 0
  camp_core: 0
  camp_sponsor: 0
  camp_user: 0
  camp_venue: 0
  ckeditor: 0
  config: 0
  config_readonly: 0
  contextual: 0
  ctools: 0
  daterange_compact: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_delimiter: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  help: 0
  honeypot: 0
  image: 0
  key: 0
  layout_discovery: 0
  link: 0
  login_destination: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailsystem: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  responsive_image: 0
  rest: 0
  sendgrid_integration: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_block: 0
  social_media_links: 0
  social_media_links_field: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  camp: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  badcamp_2018: 0
profile: camp
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
