disable_messages_enable: '1'
disable_messages_filter_by_page: 2
disable_messages_page_filter_paths: 'session/*'
disable_messages_enable_debug: '0'
disable_messages_debug_visible_div: '0'
disable_messages_ignore_patterns: '^Session (.*)? has been created.$'
disable_messages_exclude_users: ''
disable_messages_ignore_case: '1'
disable_messages_ignore_regex:
  - '/^^Session (.*)? has been created.$$/i'
_core:
  default_config_hash: 1KtMq77r11Up8xB2acdeDhrNIlFzu-Edepx453c20Ws
