mlid:
  'menu_link_content:577be616-fb17-4d70-8a5d-b076eebad004':
    roles:
      - anonymous
    access_check: false
  'menu_link_content:dd1ebf4d-362a-44d9-ba6c-669065256d36':
    roles: {  }
    access_check: false
