test_secret_key: stripe_test_secret_key
test_public_key: stripe_test_publish_key
live_secret_key: stripe_test_secret_key
live_public_key: stripe_test_publish_key
log_webhooks: 0
mode: test
_core:
  default_config_hash: bDytzWYwg0WvFxdrSzHMrWCCi82WboNTCqPbNA5oN_Q
