#!/usr/bin/env bash

#: exec_target = cli

# Abort if anything fails
set -e

SITE_DIRECTORY=${SITE_DIRECTORY:-default}

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

cd ${DOCROOT_PATH}

echo "Importing Configuration..."
drush config-import --yes

echo "Running Update.php..."
drush updatedb -y

echo "Running Drush Cache-Rebuild"
drush cr

#echo "Running Gulp Tasks on theme"
#cd ${PROJECT_ROOT}/web/themes/custom/support
#npm i -g npm@latest
#npm install -g gulp
#npm install
#gulp sass
#drush cr
